export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCEESS = 'ORDER_CREATE_SUCCEESS'
export const ORDER_CREATE_FAILURE = 'ORDER_CREATE_FAILURE'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCEESS = 'ORDER_DETAILS_SUCCEESS'
export const ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE'